# fly.toml app configuration file generated for fullstack-part11-puhelinluettelo on 2023-06-14T20:47:53+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstack-part11-puhelinluettelo"
primary_region = "arn"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
	PORT = "3001" # add this

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 3001
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "20s"
    interval = "30s"
    restart_limit = 0
    timeout = "30s"

  [[services.http_checks]]
    interval = "30s"
    grace_period = "20s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "30s"
    tls_skip_verify = false
    [services.http_checks.headers]