# fly.toml app configuration file generated for fullstack-part11-puhelinluettelo on 2023-06-14T20:47:53+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fullstack-part11-puhelinluettelo"
primary_region = "arn"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
