name: Deployment pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
        types: [opened, synchronize]

jobs:
    simple_deployment_pipeline:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '18'
            - uses: superfly/flyctl-actions/setup-flyctl@master
            - name: Install dependencies
              run: npm install
            - name: Install client dependencies
              run: npm run client-install
            - name: Check style
              run: npm run lint
            - name: Build
              run: |
                  cd puhelinluettelo
                  npm run build
                  cp -r ./build ../build
                  cd ..
                  ls -l
            - name: e2e tests
              uses: cypress-io/github-action@v5
              env:
                  MONGODB_URI: ${{ secrets.MONGODB_URI }}
              with:
                  command: npm run test:e2e
                  start: npm run start:test, npm run start:client
                  wait-on: http://localhost:3000
            - name: deploy app to fly.io
              if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')}}
              run: flyctl deploy --remote-only --wait-timeout=900
              env:
                  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
            - name: Test Success
              uses: rjstone/discord-webhook-notify@v1
              if: success()
              with:
                  text: A new version of Pokedex was deployed
                  severity: info
                  description: Commit by ${{ github.event.commits[0].committer.username }} succeeded
                  webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
            - name: Test Failure
              uses: rjstone/discord-webhook-notify@v1
              if: failure()
              with:
                  text: Build failed
                  severity: error
                  description: Commit by ${{ github.event.commits[0].committer.username }} broke the build
                  webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
    tag_release:
        needs: [simple_deployment_pipeline]
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
                with:
                    node-version: '18'
            - name: Bump version and push tag
                if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip')}}
                uses: anothrNick/github-tag-action@72703d02f7df0cdb8f27aeb9feafeccd67b49881
                env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                    DEFAULT_BUMP: patch
